/// Display names for the language codes subtitle addons and containers use
/// (ISO 639-1 two-letter and 639-2 three-letter, plus the regional forms
/// OpenSubtitles sends such as `pob`). Unknown codes come back as-is.
String languageName(String code) {
  final normalized = code.trim().toLowerCase();
  final base = normalized.split(RegExp('[-_]')).first;
  return _names[normalized] ?? _names[base] ?? code;
}

/// A language a setting such as `audioLanguage` can name: the ISO 639-2
/// three-letter [code] stremio-core stores and its display [name].
final class LanguageOption {
  const LanguageOption(this.code, this.name);

  final String code;
  final String name;
}

/// The languages the Settings dropdowns offer, one per name (the
/// bibliographic code where 639-2 has two, `fre` over `fra`, as
/// OpenSubtitles uses), sorted by name. Only three-letter codes: that is
/// what stremio-core's `Settings` carries.
final List<LanguageOption> languageOptions = () {
  final seen = <String>{};
  final options = [
    for (final MapEntry(key: code, value: name) in _names.entries)
      if (code.length == 3 && code != 'und' && seen.add(name))
        LanguageOption(code, name),
  ]..sort((a, b) => a.name.compareTo(b.name));
  return List<LanguageOption>.unmodifiable(options);
}();

const Map<String, String> _names = {
  'en': 'English',
  'eng': 'English',
  'es': 'Spanish',
  'spa': 'Spanish',
  'pt': 'Portuguese',
  'por': 'Portuguese',
  'pob': 'Portuguese (Brazil)',
  'pt-br': 'Portuguese (Brazil)',
  'fr': 'French',
  'fre': 'French',
  'fra': 'French',
  'de': 'German',
  'ger': 'German',
  'deu': 'German',
  'it': 'Italian',
  'ita': 'Italian',
  'nl': 'Dutch',
  'dut': 'Dutch',
  'nld': 'Dutch',
  'sv': 'Swedish',
  'swe': 'Swedish',
  'no': 'Norwegian',
  'nor': 'Norwegian',
  'nb': 'Norwegian',
  'da': 'Danish',
  'dan': 'Danish',
  'fi': 'Finnish',
  'fin': 'Finnish',
  'is': 'Icelandic',
  'ice': 'Icelandic',
  'isl': 'Icelandic',
  'pl': 'Polish',
  'pol': 'Polish',
  'cs': 'Czech',
  'cze': 'Czech',
  'ces': 'Czech',
  'sk': 'Slovak',
  'slo': 'Slovak',
  'slk': 'Slovak',
  'hu': 'Hungarian',
  'hun': 'Hungarian',
  'ro': 'Romanian',
  'rum': 'Romanian',
  'ron': 'Romanian',
  'bg': 'Bulgarian',
  'bul': 'Bulgarian',
  'el': 'Greek',
  'gre': 'Greek',
  'ell': 'Greek',
  'tr': 'Turkish',
  'tur': 'Turkish',
  'ru': 'Russian',
  'rus': 'Russian',
  'uk': 'Ukrainian',
  'ukr': 'Ukrainian',
  'sr': 'Serbian',
  'srp': 'Serbian',
  'hr': 'Croatian',
  'hrv': 'Croatian',
  'sl': 'Slovenian',
  'slv': 'Slovenian',
  'he': 'Hebrew',
  'heb': 'Hebrew',
  'ar': 'Arabic',
  'ara': 'Arabic',
  'fa': 'Persian',
  'per': 'Persian',
  'fas': 'Persian',
  'hi': 'Hindi',
  'hin': 'Hindi',
  'ta': 'Tamil',
  'tam': 'Tamil',
  'te': 'Telugu',
  'tel': 'Telugu',
  'bn': 'Bengali',
  'ben': 'Bengali',
  'ur': 'Urdu',
  'urd': 'Urdu',
  'th': 'Thai',
  'tha': 'Thai',
  'vi': 'Vietnamese',
  'vie': 'Vietnamese',
  'id': 'Indonesian',
  'ind': 'Indonesian',
  'ms': 'Malay',
  'may': 'Malay',
  'msa': 'Malay',
  'tl': 'Filipino',
  'fil': 'Filipino',
  'ja': 'Japanese',
  'jpn': 'Japanese',
  'ko': 'Korean',
  'kor': 'Korean',
  'zh': 'Chinese',
  'chi': 'Chinese',
  'zho': 'Chinese',
  'zh-cn': 'Chinese (Simplified)',
  'zh-tw': 'Chinese (Traditional)',
  'zht': 'Chinese (Traditional)',
  'zhe': 'Chinese (Bilingual)',
  'ca': 'Catalan',
  'cat': 'Catalan',
  'eu': 'Basque',
  'baq': 'Basque',
  'eus': 'Basque',
  'gl': 'Galician',
  'glg': 'Galician',
  'et': 'Estonian',
  'est': 'Estonian',
  'lv': 'Latvian',
  'lav': 'Latvian',
  'lt': 'Lithuanian',
  'lit': 'Lithuanian',
  'sq': 'Albanian',
  'alb': 'Albanian',
  'sqi': 'Albanian',
  'mk': 'Macedonian',
  'mac': 'Macedonian',
  'mkd': 'Macedonian',
  'bs': 'Bosnian',
  'bos': 'Bosnian',
  'ka': 'Georgian',
  'geo': 'Georgian',
  'kat': 'Georgian',
  'hy': 'Armenian',
  'arm': 'Armenian',
  'hye': 'Armenian',
  'sw': 'Swahili',
  'swa': 'Swahili',
  'af': 'Afrikaans',
  'afr': 'Afrikaans',
  'la': 'Latin',
  'lat': 'Latin',
  'eo': 'Esperanto',
  'epo': 'Esperanto',
  'und': 'Undetermined',
};
