#!/usr/bin/env bash
# Regenerates every xtremio brand asset from the geometry below.
#
# The mark is a two-tone X on the app's near-black ground: the violet arm is the
# theme seed colour, the teal arm the accent used for progress and speed. Run
# this after changing a colour or a coordinate; nothing else in the tree draws
# the icon, so this script is the source of truth.
#
# Needs ImageMagick 7 (`magick`) and Cantarell Extra Bold for the wordmark.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

BG="#0E0B16"      # scaffoldBackgroundColor
CYAN="#22D3EE"    # the mark has its own palette; the app stays violet/teal
AMBER="#F59E0B"
STROKE=31         # on the 256 grid the chevrons are drawn on
# The adaptive icon's glyph must sit inside the circle every launcher mask
# leaves visible. At full size the chevron tips reach 133 of a 128 radius, so
# the vector layers draw the same coordinates scaled about the centre.
SAFE_SCALE=0.64
INK="#F2EEFF"
FONT=$(fc-match -f "%{file}" "Cantarell:style=Extra Bold")

# ---------------------------------------------------------------- geometry --
# Two interlocking chevrons on a 256 grid: a cyan "<" and an amber ">" passing
# through each other with a diamond of ground between them. It reads as
# rewind-and-forward rather than as a letter, which is the point -- a two-tone
# X sat too close to another company's mark.
#
# Each chevron is a round-capped, round-joined polyline of width 31.
# ImageMagick's own renderer draws neither strokes nor gradients (both were
# found the hard way), so raster output writes the stroke out as what it
# geometrically is: a quad per segment plus a disc at each vertex. The Android
# vector drawables keep the real stroke, which AAPT does support.
LEFT_CHEVRON="206,40 50,128 206,216"
RIGHT_CHEVRON="50,40 206,128 50,216"

mark_svg() { # $1=background(or "none") $2=left-colour $3=right-colour
  python3 -c '
import math, sys
bg, cyan, amber, left, right, width = sys.argv[1:7]
w = float(width)

def stroked(spec):
    pts = [tuple(float(v) for v in q.split(",")) for q in spec.split()]
    r, out = w / 2, []
    for (x1, y1), (x2, y2) in zip(pts, pts[1:]):
        dx, dy = x2 - x1, y2 - y1
        L = math.hypot(dx, dy)
        nx, ny = -dy / L * r, dx / L * r
        c = [(x1 + nx, y1 + ny), (x2 + nx, y2 + ny),
             (x2 - nx, y2 - ny), (x1 - nx, y1 - ny)]
        out.append("<polygon points=\"%s\"/>" % " ".join("%.2f,%.2f" % v for v in c))
    out += ["<circle cx=\"%g\" cy=\"%g\" r=\"%g\"/>" % (x, y, r) for x, y in pts]
    return "".join(out)

parts = ["<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 256 256\" width=\"1024\" height=\"1024\">"]
if bg != "none":
    parts.append("<rect width=\"256\" height=\"256\" fill=\"%s\"/>" % bg)
parts.append("<g fill=\"%s\">%s</g>" % (cyan, stroked(left)))
parts.append("<g fill=\"%s\">%s</g>" % (amber, stroked(right)))
sys.stdout.write("".join(parts) + "</svg>")
' "$1" "$2" "$3" "$LEFT_CHEVRON" "$RIGHT_CHEVRON" "$STROKE"
}

mark_svg "$BG" "$CYAN" "$AMBER" > "$OUT/flat.svg"
mark_svg black white white > "$OUT/stencil.svg"

cut_out() { # $1=size $2=out -- the mark on transparency
  magick "$OUT/flat.svg" -resize "${1}x${1}" \
    \( "$OUT/stencil.svg" -resize "${1}x${1}" -colorspace gray -alpha off \) \
    -alpha off -compose CopyOpacity -composite "$2"
}

# ------------------------------------------------------------ shared source --
mark_svg "$BG" "$CYAN" "$AMBER" > assets/branding/xtremio-mark.svg
cut_out 1024 assets/branding/xtremio-mark-1024.png

# ------------------------------------------------------- android adaptive ----
RES=android/app/src/main/res
mkdir -p "$RES/mipmap-anydpi-v26" "$RES/drawable" "$RES/values"

vector() { # $1=file $2=paths-as-android-xml
  cat > "$1" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="256"
    android:viewportHeight="256">
$2</vector>
XML
}
# The two vector layers keep the real stroke, which AAPT supports and which
# keeps the file a few hundred bytes. The group scales the same coordinates the
# rasters use into the circle every launcher mask leaves visible.
chevron_vector() { # $1=file $2=left-colour $3=right-colour
  cat > "$1" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="256"
    android:viewportHeight="256">
    <group
        android:scaleX="$SAFE_SCALE"
        android:scaleY="$SAFE_SCALE"
        android:pivotX="128"
        android:pivotY="128">
        <path
            android:pathData="M206,40 L50,128 L206,216"
            android:strokeColor="$2"
            android:strokeWidth="$STROKE"
            android:strokeLineCap="round"
            android:strokeLineJoin="round"/>
        <path
            android:pathData="M50,40 L206,128 L50,216"
            android:strokeColor="$3"
            android:strokeWidth="$STROKE"
            android:strokeLineCap="round"
            android:strokeLineJoin="round"/>
    </group>
</vector>
XML
}

chevron_vector "$RES/drawable/ic_launcher_foreground.xml" "$CYAN" "$AMBER"
# The themed-icon layer is tinted by the launcher, so it is one flat colour.
chevron_vector "$RES/drawable/ic_launcher_monochrome.xml" "#FFFFFF" "#FFFFFF"

cat > "$RES/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<resources>
    <color name="ic_launcher_background">$BG</color>
</resources>
XML

for name in ic_launcher ic_launcher_round; do
  cat > "$RES/mipmap-anydpi-v26/$name.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
XML
done

# --------------------------------------------- android legacy raster icons --
# Pre-Oreo launchers draw these unmasked, so they carry their own rounded
# corners; the round variant is what a circular launcher asks for by name.
render_flat() { # $1=size $2=out  -- opaque; the App Store rejects icons with alpha
  magick "$OUT/flat.svg" -resize "${1}x${1}" -background "$BG" -alpha remove -alpha off "$2"
}
round_corner_mask() { # $1=size -> writes $OUT/rc.png
  local s=$1 r=$(( $1 * 22 / 100 ))
  magick -size "${s}x${s}" xc:none -fill white \
    -draw "roundrectangle 0,0 $((s-1)),$((s-1)) $r,$r" "$OUT/rc.png"
}
circle_mask() { # $1=size -> writes $OUT/ci.png
  local s=$1 c
  c=$(( (s - 1) / 2 ))
  magick -size "${s}x${s}" xc:none -fill white \
    -draw "circle $c,$c $c,0" "$OUT/ci.png"
}
i=0
for d in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
  size=$(echo "48 72 96 144 192" | cut -d' ' -f$((i+1))); i=$((i+1))
  mkdir -p "$RES/mipmap-$d"
  render_flat "$size" "$OUT/sq.png"
  round_corner_mask "$size"
  magick "$OUT/sq.png" "$OUT/rc.png" -alpha off -compose CopyOpacity -composite \
    "$RES/mipmap-$d/ic_launcher.png"
  circle_mask "$size"
  magick "$OUT/sq.png" "$OUT/ci.png" -alpha off -compose CopyOpacity -composite \
    "$RES/mipmap-$d/ic_launcher_round.png"
done

# ---------------------------------------------------------------- lockup ----
# The wordmark uses the mark itself as the x in "xtremio", so the X is scaled
# to the font's x-height (with the overshoot a pointed glyph wants) and sat on
# the same baseline as the remaining letters.
lockup() { # $1=pointsize $2=out (transparent png)
  local ps=$1 out=$2 xh s ink top gap tx base canvas marky
  xh=$(magick -font "$FONT" -pointsize "$ps" label:x -trim -format "%h" info:)
  # the X ink fills 64 of the 108 grid, so the raster has to be scaled past the
  # height we actually want to see
  # The mark's ink, caps included, spans 24.5..231.5 of the 256 grid: 81% of
  # the raster, where the old X filled 59%. It is also a symbol rather than a
  # letter, so it is set a little taller than the x-height and centred on that
  # band, overshooting it evenly above and below the way a round glyph does.
  s=$(awk -v x="$xh" 'BEGIN{printf "%d", x * 1.30 * 256 / 207}')
  ink=$(awk -v s="$s" 'BEGIN{printf "%d", s * 207 / 256}')
  top=$(awk -v s="$s" 'BEGIN{printf "%d", s * 24.5 / 256}')
  gap=$(awk -v x="$xh" 'BEGIN{printf "%d", x * 0.30}')
  base=$((ps * 3))
  tx=$((60 + ink + gap))
  canvas=$((tx + ps * 6))
  # Centre the overshoot on the x-height band rather than sitting the ink on
  # the baseline: a symmetrical mark reads as sunk when its foot is the datum.
  marky=$(awk -v b="$base" -v t="$top" -v i="$ink" -v x="$xh" \
    'BEGIN{printf "%d", b - t - i + (i - x) / 2}')
  cut_out "$s" "$OUT/lockup_mark.png"
  magick -size "${canvas}x$((base + ps))" xc:none \
    "$OUT/lockup_mark.png" -geometry "+60+${marky}" -composite \
    -font "$FONT" -pointsize "$ps" -fill "$INK" -gravity none \
    -annotate "+${tx}+${base}" "tremio" \
    -trim +repage "$out"
}
lockup 140 "$OUT/lockup.png"

# ------------------------------------------------------------- TV banner ----
# The leanback launcher shows a 320x180 xhdpi banner instead of the square icon.
magick -size 320x180 "xc:$BG" \
  \( "$OUT/lockup.png" -resize 252x104 \) -gravity center -composite \
  "$RES/drawable-xhdpi/banner.png"

# ---------------------------------------------------------- desktop / iOS ----
for s in 16 32 64 128 256 512 1024; do
  render_flat "$s" "macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_$s.png"
done
while read -r size file; do
  render_flat "$size" "ios/Runner/Assets.xcassets/AppIcon.appiconset/$file"
done <<'IOS'
40 Icon-App-20x20@2x.png
60 Icon-App-20x20@3x.png
20 Icon-App-20x20@1x.png
29 Icon-App-29x29@1x.png
58 Icon-App-29x29@2x.png
87 Icon-App-29x29@3x.png
40 Icon-App-40x40@1x.png
80 Icon-App-40x40@2x.png
120 Icon-App-40x40@3x.png
120 Icon-App-60x60@2x.png
180 Icon-App-60x60@3x.png
76 Icon-App-76x76@1x.png
152 Icon-App-76x76@2x.png
167 Icon-App-83.5x83.5@2x.png
1024 Icon-App-1024x1024@1x.png
IOS
for s in 16 24 32 48 64 128 256; do render_flat "$s" "$OUT/ico_$s.png"; done
magick "$OUT/ico_16.png" "$OUT/ico_24.png" "$OUT/ico_32.png" "$OUT/ico_48.png" \
  "$OUT/ico_64.png" "$OUT/ico_128.png" "$OUT/ico_256.png" windows/runner/resources/app_icon.ico

# The .desktop entry says Icon=com.zond.xtremio, so a packager needs a file of
# that name to install into hicolor/512x512/apps.
render_flat 512 linux/com.zond.xtremio.png

# ------------------------------------------------------------------ logo ----
# Horizontal lockup for the README and anywhere the name needs to appear.
magick "$OUT/lockup.png" -bordercolor none -border 56 \
  -background "$BG" -alpha remove -alpha off assets/branding/xtremio-logo.png

echo "brand assets regenerated"
