#!/usr/bin/env bash
# Regenerates every xtremio brand asset from the geometry below.
#
# The mark is a two-tone X on the app's near-black ground: the violet arm is the
# theme seed colour, the teal arm the accent used for progress and speed. Run
# this after changing a colour or a coordinate; nothing else in the tree draws
# the icon, so this script is the source of truth.
#
# Needs ImageMagick 7 (`magick`) and Cantarell Extra Bold for the wordmark.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

BG="#0E0B16"      # scaffoldBackgroundColor
VIOLET="#8E6BFF"  # lighter sibling of the 0xFF7B5BF5 seed
TEAL="#2ED9C3"
INK="#F2EEFF"
FONT=$(fc-match -f "%{file}" "Cantarell:style=Extra Bold")

# ---------------------------------------------------------------- geometry --
# All coordinates live on the 108x108 adaptive-icon grid. `mark` draws the X
# with a given bounding box and arm thickness; the adaptive foreground keeps the
# glyph inside the 72dp circle that every launcher mask leaves visible, while
# the flat icons can run wider because nothing crops them.
mark_paths() { # $1=x0 $2=x1 $3=thickness  -> two <path> elements, teal under violet
  local a=$1 b=$2 t=$3
  printf '<path d="M%s %s L%s %s L%s %s L%s %s Z" fill="%s"/>' \
    "$b" "$a" "$((b-t))" "$a" "$a" "$b" "$((a+t))" "$b" "$TEAL"
  printf '<path d="M%s %s L%s %s L%s %s L%s %s Z" fill="%s"/>' \
    "$a" "$a" "$((a+t))" "$a" "$b" "$b" "$((b-t))" "$b" "$VIOLET"
}
FG_PATHS=$(mark_paths 30 78 14)   # adaptive foreground, safe inside the mask
FLAT_PATHS=$(mark_paths 22 86 19) # flat square icons, full bleed

svg() { # $1=background-fill(or none) $2=paths -> stdout
  printf '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="1024" height="1024">'
  [ "$1" = none ] || printf '<rect width="108" height="108" fill="%s"/>' "$1"
  printf '%s</svg>' "$2"
}

svg "$BG" "$FLAT_PATHS" > "$OUT/flat.svg"

# ImageMagick's built-in SVG renderer loses paths drawn on a background-less
# canvas, so cut-outs come from a black/white stencil composited as alpha.
stencil() { # $1=paths -> stdout
  printf '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="1024" height="1024">'
  printf '<rect width="108" height="108" fill="black"/>'
  printf '%s' "$1" | sed 's/fill="[^"]*"/fill="white"/g'
  printf '</svg>'
}
stencil "$FLAT_PATHS" > "$OUT/stencil.svg"

cut_out() { # $1=size $2=out  -- the mark on transparency
  magick "$OUT/flat.svg" -resize "${1}x${1}" \
    \( "$OUT/stencil.svg" -resize "${1}x${1}" -colorspace gray -alpha off \) \
    -alpha off -compose CopyOpacity -composite "$2"
}

# ------------------------------------------------------------ shared source --
svg "$BG" "$FLAT_PATHS" > assets/branding/xtremio-mark.svg
cut_out 1024 assets/branding/xtremio-mark-1024.png

# ------------------------------------------------------- android adaptive ----
RES=android/app/src/main/res
mkdir -p "$RES/mipmap-anydpi-v26" "$RES/drawable" "$RES/values"

vector() { # $1=file $2=paths-as-android-xml
  cat > "$1" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
$2</vector>
XML
}
vector "$RES/drawable/ic_launcher_foreground.xml" \
"    <path android:pathData=\"M78,30 L64,30 L30,78 L44,78 Z\" android:fillColor=\"$TEAL\"/>
    <path android:pathData=\"M30,30 L44,30 L78,78 L64,78 Z\" android:fillColor=\"$VIOLET\"/>"
# The themed-icon layer is tinted by the launcher, so it is one flat colour.
vector "$RES/drawable/ic_launcher_monochrome.xml" \
"    <path android:pathData=\"M78,30 L64,30 L30,78 L44,78 Z\" android:fillColor=\"#FFFFFF\"/>
    <path android:pathData=\"M30,30 L44,30 L78,78 L64,78 Z\" android:fillColor=\"#FFFFFF\"/>"

cat > "$RES/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<resources>
    <color name="ic_launcher_background">$BG</color>
</resources>
XML

for name in ic_launcher ic_launcher_round; do
  cat > "$RES/mipmap-anydpi-v26/$name.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_branding.sh; edit that script, not this file. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
XML
done

# --------------------------------------------- android legacy raster icons --
# Pre-Oreo launchers draw these unmasked, so they carry their own rounded
# corners; the round variant is what a circular launcher asks for by name.
render_flat() { # $1=size $2=out  -- opaque; the App Store rejects icons with alpha
  magick "$OUT/flat.svg" -resize "${1}x${1}" -background "$BG" -alpha remove -alpha off "$2"
}
round_corner_mask() { # $1=size -> writes $OUT/rc.png
  local s=$1 r=$(( $1 * 22 / 100 ))
  magick -size "${s}x${s}" xc:none -fill white \
    -draw "roundrectangle 0,0 $((s-1)),$((s-1)) $r,$r" "$OUT/rc.png"
}
circle_mask() { # $1=size -> writes $OUT/ci.png
  local s=$1 c
  c=$(( (s - 1) / 2 ))
  magick -size "${s}x${s}" xc:none -fill white \
    -draw "circle $c,$c $c,0" "$OUT/ci.png"
}
i=0
for d in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
  size=$(echo "48 72 96 144 192" | cut -d' ' -f$((i+1))); i=$((i+1))
  mkdir -p "$RES/mipmap-$d"
  render_flat "$size" "$OUT/sq.png"
  round_corner_mask "$size"
  magick "$OUT/sq.png" "$OUT/rc.png" -alpha off -compose CopyOpacity -composite \
    "$RES/mipmap-$d/ic_launcher.png"
  circle_mask "$size"
  magick "$OUT/sq.png" "$OUT/ci.png" -alpha off -compose CopyOpacity -composite \
    "$RES/mipmap-$d/ic_launcher_round.png"
done

# ---------------------------------------------------------------- lockup ----
# The wordmark uses the mark itself as the x in "xtremio", so the X is scaled
# to the font's x-height (with the overshoot a pointed glyph wants) and sat on
# the same baseline as the remaining letters.
lockup() { # $1=pointsize $2=out (transparent png)
  local ps=$1 out=$2 xh s ink top gap tx base canvas marky
  xh=$(magick -font "$FONT" -pointsize "$ps" label:x -trim -format "%h" info:)
  # the X ink fills 64 of the 108 grid, so the raster has to be scaled past the
  # height we actually want to see
  s=$(awk -v x="$xh" 'BEGIN{printf "%d", x * 1.06 * 108 / 64}')
  ink=$(awk -v s="$s" 'BEGIN{printf "%d", s * 64 / 108}')
  top=$(awk -v s="$s" 'BEGIN{printf "%d", s * 22 / 108}')
  gap=$(awk -v x="$xh" 'BEGIN{printf "%d", x * 0.20}')
  base=$((ps * 3))
  tx=$((60 + ink + gap))
  canvas=$((tx + ps * 6))
  marky=$((base - top - ink))
  cut_out "$s" "$OUT/lockup_mark.png"
  magick -size "${canvas}x$((base + ps))" xc:none \
    "$OUT/lockup_mark.png" -geometry "+60+${marky}" -composite \
    -font "$FONT" -pointsize "$ps" -fill "$INK" -gravity none \
    -annotate "+${tx}+${base}" "tremio" \
    -trim +repage "$out"
}
lockup 140 "$OUT/lockup.png"

# ------------------------------------------------------------- TV banner ----
# The leanback launcher shows a 320x180 xhdpi banner instead of the square icon.
magick -size 320x180 "xc:$BG" \
  \( "$OUT/lockup.png" -resize 252x104 \) -gravity center -composite \
  "$RES/drawable-xhdpi/banner.png"

# ---------------------------------------------------------- desktop / iOS ----
for s in 16 32 64 128 256 512 1024; do
  render_flat "$s" "macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_$s.png"
done
while read -r size file; do
  render_flat "$size" "ios/Runner/Assets.xcassets/AppIcon.appiconset/$file"
done <<'IOS'
40 Icon-App-20x20@2x.png
60 Icon-App-20x20@3x.png
20 Icon-App-20x20@1x.png
29 Icon-App-29x29@1x.png
58 Icon-App-29x29@2x.png
87 Icon-App-29x29@3x.png
40 Icon-App-40x40@1x.png
80 Icon-App-40x40@2x.png
120 Icon-App-40x40@3x.png
120 Icon-App-60x60@2x.png
180 Icon-App-60x60@3x.png
76 Icon-App-76x76@1x.png
152 Icon-App-76x76@2x.png
167 Icon-App-83.5x83.5@2x.png
1024 Icon-App-1024x1024@1x.png
IOS
for s in 16 24 32 48 64 128 256; do render_flat "$s" "$OUT/ico_$s.png"; done
magick "$OUT/ico_16.png" "$OUT/ico_24.png" "$OUT/ico_32.png" "$OUT/ico_48.png" \
  "$OUT/ico_64.png" "$OUT/ico_128.png" "$OUT/ico_256.png" windows/runner/resources/app_icon.ico

# The .desktop entry says Icon=com.zond.xtremio, so a packager needs a file of
# that name to install into hicolor/512x512/apps.
render_flat 512 linux/com.zond.xtremio.png

# ------------------------------------------------------------------ logo ----
# Horizontal lockup for the README and anywhere the name needs to appear.
magick "$OUT/lockup.png" -bordercolor none -border 56 \
  -background "$BG" -alpha remove -alpha off assets/branding/xtremio-logo.png

echo "brand assets regenerated"
