#!/usr/bin/env bash
# Measures where the FFmpeg struct fields `rust/src/libav.rs` reads sit, for
# the FFmpeg the vendored libmpv carries, on a 64-bit and a 32-bit target.
#
# `rust/src/libav.rs` reads FFmpeg's structs by layout, transcribed as
# prefixes, and asserts every field it reads at the offsets this prints
# (its `layout` module). Run it when the vendored `media_kit_libs_android_video`
# moves to another FFmpeg: find the version first --
#   strings libmpv.so | grep -E '^FFmpeg version|^Lavf[0-9]'
# -- then `tool/libav_offsets.sh 6.0` (the release, as ffmpeg.org names its
# tarballs), and re-transcribe the prefixes and the assertions from what it
# prints. Within one major the offsets do not move (fields are only appended),
# which is why the host's own FFmpeg can stand in for the device's in tests.
#
# Needs curl, gcc and an Android NDK (`ANDROID_NDK_HOME`, or the newest under
# ~/Android/Sdk/ndk) for the 32-bit ARM layout.
set -euo pipefail

VERSION=${1:?usage: $0 <ffmpeg release, e.g. 6.0>}
NDK=${ANDROID_NDK_HOME:-$(ls -d "$HOME"/Android/Sdk/ndk/* | sort -V | tail -1)}
CLANG="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

curl -sSfL "https://ffmpeg.org/releases/ffmpeg-$VERSION.tar.xz" -o "$WORK/ffmpeg.tar.xz"
tar -C "$WORK" -xf "$WORK/ffmpeg.tar.xz" \
  "ffmpeg-$VERSION/libavformat" "ffmpeg-$VERSION/libavcodec" "ffmpeg-$VERSION/libavutil"
SRC="$WORK/ffmpeg-$VERSION"
# Generated by configure in a real build; the headers need them to parse.
printf '#define AV_HAVE_BIGENDIAN 0\n#define AV_HAVE_FAST_UNALIGNED 1\n' > "$SRC/libavutil/avconfig.h"
echo "#define FFMPEG_VERSION \"$VERSION\"" > "$SRC/libavutil/ffversion.h"

cat > "$WORK/offsets.c" <<'EOF'
#include <stddef.h>
#include "libavformat/avformat.h"
#include "libavformat/avio.h"
#include "libavcodec/packet.h"
#include "libavcodec/codec_par.h"
#define O(T, f) const unsigned long off_##T##__##f = offsetof(T, f);
O(AVFormatContext, pb) O(AVFormatContext, nb_streams) O(AVFormatContext, streams)
O(AVFormatContext, start_time) O(AVFormatContext, duration)
O(AVStream, index) O(AVStream, codecpar) O(AVStream, time_base) O(AVStream, disposition)
O(AVCodecParameters, codec_type) O(AVCodecParameters, codec_id)
O(AVCodecParameters, extradata) O(AVCodecParameters, extradata_size)
O(AVCodecParameters, width) O(AVCodecParameters, height)
O(AVCodecParameters, sample_rate) O(AVCodecParameters, ch_layout)
O(AVChannelLayout, nb_channels)
O(AVPacket, pts) O(AVPacket, dts) O(AVPacket, data) O(AVPacket, size)
O(AVPacket, stream_index) O(AVPacket, flags) O(AVPacket, duration)
O(AVIOContext, buffer)
const unsigned long id_h264 = AV_CODEC_ID_H264, id_hevc = AV_CODEC_ID_HEVC,
    id_aac = AV_CODEC_ID_AAC;
EOF

for target in x86_64-linux-gnu armv7a-linux-androideabi24; do
  if [ "$target" = x86_64-linux-gnu ]; then cc=(gcc); else cc=("$CLANG" "--target=$target"); fi
  "${cc[@]}" -I"$SRC" -O0 -S "$WORK/offsets.c" -o "$WORK/$target.s"
  echo "== $target"
  # Each constant is a label followed by one data directive (`.zero` for 0).
  awk '/^(off|id)_/ { name = $1 }
       /\.(quad|long|word|zero)/ { if (name) { sub(":", "", name); print "  " name " = " ($1 == ".zero" ? 0 : $2); name = "" } }' \
    "$WORK/$target.s"
done
