// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How every addon has been answering, as one JSON object.
///
/// `addons` maps a record key to that addon's resource kinds, and each of
/// those to `{"ok","empty","fail","lastOk","lastFail","updated"}`.
///
/// `ok`/`empty`/`fail` are decayed counts as of `updated`, and the app ages
/// them the rest of the way to now; the three are separate because "the
/// addon answered with nothing" is not "the addon failed". `resource` is
/// `catalog`, `meta`, `stream` or `subtitles`.
///
/// `everyAnswerFailed` is true when nothing has answered at all since this
/// run started, which is a statement about the connection rather than about
/// any addon -- such a sweep is recorded against nobody, so it leaves no
/// trace in the counts and has to be reported separately.
///
/// Async even though it only clones at most a couple of hundred small
/// records: it takes the same lock the flush holds across a whole
/// preferences rewrite, which ends in an fsync and a rename. Handed to
/// Dart synchronously it would make the UI thread wait out that write.
/// Empty before `core_init` and after `shutdown`.
Future<String> addonHealthReport() =>
    RustLib.instance.api.crateApiAddonHealthAddonHealthReport();

/// Drops everything recorded about one addon, answering whether there was
/// anything to drop.
///
/// `key` is the record's key, not a URL. Writes the table out at once
/// rather than waiting for the flush throttle, so the record cannot come
/// back after a restart either. Async: it fsyncs and renames the
/// preferences file.
Future<bool> addonHealthForget({required String key}) =>
    RustLib.instance.api.crateApiAddonHealthAddonHealthForget(key: key);
