// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'server.dart';

/// Runtime events as JSON strings, one per item. Either
/// `{"name":"NewState","args":["board","ctx"]}` (the fields that changed) or
/// `{"name":"CoreEvent","args":{...}}`. Subscribe before `core_init`; events
/// emitted earlier are replayed from a bounded buffer.
Stream<String> coreEvents() => RustLib.instance.api.crateApiCoreCoreEvents();

/// Boots the engine (idempotent). Blocks the FRB worker for the duration of
/// storage hydration and server start-up; never call from the UI thread.
Future<CoreInitResult> coreInit({required CoreConfig config}) =>
    RustLib.instance.api.crateApiCoreCoreInit(config: config);

/// Dispatches `{"field": <"board"|...|null>, "action": <stremio_core Action>}`.
/// Malformed JSON is an error naming the offending path.
Future<void> coreDispatch({required String actionJson}) =>
    RustLib.instance.api.crateApiCoreCoreDispatch(actionJson: actionJson);

/// Serializes one model field (`snake_case`, e.g. `"streaming_server"`).
Future<String> coreGetState({required String field}) =>
    RustLib.instance.api.crateApiCoreCoreGetState(field: field);

/// Whether `core_init` has completed and `core_shutdown` has not run since.
bool coreIsInitialized() =>
    RustLib.instance.api.crateApiCoreCoreIsInitialized();

/// Stops the engine and the embedded server.
Future<void> coreShutdown() => RustLib.instance.api.crateApiCoreCoreShutdown();

/// Boot configuration. Directories come from Dart (`path_provider`).
class CoreConfig {
  /// Where stremio-core persists its buckets (`<key>.json`).
  final String storageDir;

  /// Reserved for an HTTP cache; created but unused for now.
  final String cacheDir;

  /// When set, the embedded server is started first and the engine is
  /// pointed at it (unless the profile names a remote server).
  final ServerConfig? server;

  const CoreConfig({
    required this.storageDir,
    required this.cacheDir,
    this.server,
  });

  @override
  int get hashCode => storageDir.hashCode ^ cacheDir.hashCode ^ server.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          storageDir == other.storageDir &&
          cacheDir == other.cacheDir &&
          server == other.server;
}

class CoreInitResult {
  /// Base URL of the embedded server, when one was started.
  final String? serverBaseUrl;

  /// stremio-core's `SCHEMA_VERSION`.
  final int schemaVersion;

  const CoreInitResult({this.serverBaseUrl, required this.schemaVersion});

  @override
  int get hashCode => serverBaseUrl.hashCode ^ schemaVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreInitResult &&
          runtimeType == other.runtimeType &&
          serverBaseUrl == other.serverBaseUrl &&
          schemaVersion == other.schemaVersion;
}
