// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The snapshot. Cheap enough for the UI thread: a lock, a clone of a few
/// hundred short strings, and no I/O.
DiagnosticsSnapshot diagnosticsSnapshot() =>
    RustLib.instance.api.crateApiDiagnosticsDiagnosticsSnapshot();

/// Records one line from the Dart side into the same ring the Rust log
/// fills, so a report can explain a failure that happened above the FFI --
/// a player open that was refused and retried, an engine error out of
/// media_kit, an unhandled Flutter error. Without this the ring holds only
/// the Rust half of a session and a playback failure leaves no trace in it
/// at all.
///
/// Sync on purpose: the line is written where it happened, so the ring's
/// order stays the order things occurred in rather than the order a worker
/// pool got to them. `level` is `error`/`warn`/`info`/`debug` (anything
/// else is info) and `target` names the Dart source (`player`, `flutter`).
/// A message longer than [`crate::logging::MAX_APP_MESSAGE`] is cut.
///
/// **Nothing secret may be passed here.** The caller sanitizes (no event
/// args, no auth material, no manifest URL with a key), and the Dart side
/// redacts again on the way to the clipboard; this is the middle of that
/// sandwich, not a place to be careless.
void diagnosticsLog({
  required String level,
  required String target,
  required String message,
}) => RustLib.instance.api.crateApiDiagnosticsDiagnosticsLog(
  level: level,
  target: target,
  message: message,
);

/// Everything the Rust side can say about itself in one call.
class DiagnosticsSnapshot {
  /// `xtremio_core`'s crate version.
  final String coreVersion;

  /// The git revision the embedded stream-server is pinned to, when it is
  /// still a git pin.
  final String? streamServerRev;

  /// The git revision stremio-core is pinned to.
  final String? stremioCoreRev;

  /// Base URL of the embedded server, or null when it is not running --
  /// which is also how the app tells whether it is.
  final String? serverBaseUrl;

  /// The captured `tracing` lines, oldest first: this crate's and the
  /// embedded server's, both through the one subscriber, bounded by
  /// `crate::logging::RING_CAPACITY`.
  final List<String> logLines;

  const DiagnosticsSnapshot({
    required this.coreVersion,
    this.streamServerRev,
    this.stremioCoreRev,
    this.serverBaseUrl,
    required this.logLines,
  });

  @override
  int get hashCode =>
      coreVersion.hashCode ^
      streamServerRev.hashCode ^
      stremioCoreRev.hashCode ^
      serverBaseUrl.hashCode ^
      logLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticsSnapshot &&
          runtimeType == other.runtimeType &&
          coreVersion == other.coreVersion &&
          streamServerRev == other.streamServerRev &&
          stremioCoreRev == other.stremioCoreRev &&
          serverBaseUrl == other.serverBaseUrl &&
          logLines == other.logLines;
}
