// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Registers `streaming_url` -- a URL stremio-core built on the embedded
/// server (a torrent's `/{infoHash}/{fileIdx}`) -- and answers the id mpv
/// is handed as `xtremio://<id>`. No I/O. Errors when the server is not
/// running.
String mediaRegister({required String streamingUrl}) =>
    RustLib.instance.api.crateApiMediaMediaRegister(streamingUrl: streamingUrl);

/// What `id` is, as JSON: `{name, contentType, len, member, inProcess,
/// proxyUrl}` once resolved, or `{refused, message}` when the server will
/// not play it -- a refusal is an answer. Waits while the server adds the
/// torrent and chooses its file (up to the metadata timeout for a
/// magnet), so it runs on a worker; the reader mpv opens afterwards finds
/// the answer kept. Errors when the server is not running.
Future<String> mediaResolve({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaResolve(id: id);

/// The play mpv's reader over `id` will be: this player's `token`
/// (`<viewer>.<screen>`, what `p=` carried) and its read-ahead `buffer`
/// (`normal`, `large`, `maximum`). Set before handing mpv the id; an open
/// without one is an aside, which shares nothing and moves no play.
void mediaSetPlay({
  required String id,
  required String token,
  required String buffer,
}) => RustLib.instance.api.crateApiMediaMediaSetPlay(
  id: id,
  token: token,
  buffer: buffer,
);

/// The viewer changed the read-ahead for `id`. The open reader takes it at
/// its next reopen -- a seek -- and nothing reopens the player for it.
/// Errors when the server is not running or holds nothing under `id`.
void mediaSetBuffer({required String id, required String buffer}) =>
    RustLib.instance.api.crateApiMediaMediaSetBuffer(id: id, buffer: buffer);

/// `server_stream_numbers` for what `id` resolved to, as JSON, or null
/// for an id not resolved yet. Errors when the server is not running.
Future<String?> mediaStreamNumbers({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaStreamNumbers(id: id);

/// How long the film behind `id` is (`server_note_duration`, by id). A
/// hint: never errors, and a length that is not one is dropped.
Future<void> mediaNoteDuration({
  required String id,
  required double durationSeconds,
}) => RustLib.instance.api.crateApiMediaMediaNoteDuration(
  id: id,
  durationSeconds: durationSeconds,
);

/// A player opened on `id` (`server_note_player_opened`, by id). A hint:
/// never errors.
Future<void> mediaNotePlayerOpened({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaNotePlayerOpened(id: id);

/// The player of `id` is buffering after having played
/// (`server_note_player_stalled`, by id). A hint: never errors.
Future<void> mediaNotePlayerStalled({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaNotePlayerStalled(id: id);

/// Registers the `xtremio` protocol on the mpv handle at `ctx` (media_kit's
/// `NativePlayer.ctx.address`), resolving libmpv's stream_cb API from the
/// library at `libmpv_path` (`NativeLibrary.path`). Once per player, after
/// `waitForPlayerInitialization` and before the first open; a second call
/// on the same handle is a no-op. Answers whether this call registered it
/// (`false`: it was there already). Errors for a null handle or a libmpv
/// without the API.
Future<bool> mpvStreamRegister({
  required PlatformInt64 ctx,
  required String libmpvPath,
}) => RustLib.instance.api.crateApiMediaMpvStreamRegister(
  ctx: ctx,
  libmpvPath: libmpvPath,
);
