// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Registers `streaming_url` -- a URL stremio-core built on the embedded
/// server (a torrent's `/{infoHash}/{fileIdx}`, a `/proxy` link, an
/// archive member's `/{fmt}/create` or `/{fmt}/stream`) -- and answers the
/// id mpv
/// is handed as `xtremio://<id>`. No I/O. Errors when the server is not
/// running.
String mediaRegister({required String streamingUrl}) =>
    RustLib.instance.api.crateApiMediaMediaRegister(streamingUrl: streamingUrl);

/// Registers the linked Google Drive file `file_id` (what an
/// `xtremio-drive:<fileId>` stream names) and answers its id. The grant is
/// the one the app handed Rust (`server_drive_grant`), read when the
/// server resolves; a finished download of the file needs none. No I/O.
/// Errors when the server is not running.
String mediaRegisterDrive({required String fileId, String? name}) => RustLib
    .instance
    .api
    .crateApiMediaMediaRegisterDrive(fileId: fileId, name: name);

/// Registers a file on this device by its `path` and answers its id;
/// `name` is what to call it (the path's file name when null). No I/O.
/// Errors when the server is not running.
String mediaRegisterLocalPath({required String path, String? name}) => RustLib
    .instance
    .api
    .crateApiMediaMediaRegisterLocalPath(path: path, name: name);

/// Registers a file on this device by a descriptor the app has detached
/// (Android's `ParcelFileDescriptor.detachFd()`) and answers its id. **The
/// descriptor is Rust's from this call on**, answered or not: an error
/// closes it. `name` is what to call it -- a descriptor has no name, and
/// its extension is where the content type comes from. Errors when the
/// server is not running, and on a platform with no descriptors.
String mediaRegisterLocalFd({required PlatformInt64 fd, String? name}) =>
    RustLib.instance.api.crateApiMediaMediaRegisterLocalFd(fd: fd, name: name);

/// Publishes `id` for a cast and answers the token the receiver's URL ends
/// in (`<lan base>/cast/<token>`); the play `media_set_play` recorded for
/// the id goes with it. **A URL into this device while published: never
/// log it.** Errors while the LAN listener is not running, or for an id
/// the server does not hold.
Future<String> mediaPublish({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaPublish(id: id);

/// Publishes a rendition of `id` for a cast -- one fragmented MP4 the
/// server makes from the film as the receiver reads it -- and answers the
/// token its stream is under (`<lan base>/cast/<token>/stream.mp4`); the
/// play `media_set_play` recorded for the id goes with it. `spec` is the
/// server's `RenditionSpec` as JSON (`durationMs`, `segmentMs`, `startMs`,
/// `video`, `audio`, `audioTrack`). **A URL into this device while
/// published: never log it.** Errors as `media_publish` does, and for a
/// spec that is not one.
Future<String> mediaPublishRendition({
  required String id,
  required String spec,
}) =>
    RustLib.instance.api.crateApiMediaMediaPublishRendition(id: id, spec: spec);

/// Starts making the published rendition `token`'s start -- the source's
/// index, the header, the slot the receiver will begin in -- with no
/// receiver asking yet, so the app hands the receiver the stream only once
/// [`media_rendition_readiness`] says it is ready. Returns at once; the
/// work waits as long as the source takes, and an unpublish ends it.
/// Whether `token` is a published rendition.
bool mediaPrepareRendition({required String token}) =>
    RustLib.instance.api.crateApiMediaMediaPrepareRendition(token: token);

/// How far the rendition `token` has got, as JSON: `{"phase": "index"}`,
/// `"start"`, `"ready"`, `"failed"` with the `sentence` to show, or
/// `"ended"` (not published). Cheap; polled.
String mediaRenditionReadiness({required String token}) =>
    RustLib.instance.api.crateApiMediaMediaRenditionReadiness(token: token);

/// What the publication `token` has served so far, as JSON -- the
/// server's `CastNumbers`: `kind` (`plain`, `rendition`), `contentType`,
/// `delivery` (requests, bodies begun, ended and open, bytes, where the
/// latest body began, the furthest byte sent), `source` (its kind, bytes
/// read, opens, seeks) and for a rendition what it has made -- or `None`
/// once it is not published. Counts that only grow, no rate: the caller
/// divides two answers by the time between them. Cheap; polled while the
/// cast panel is up.
String? mediaCastNumbers({required String token}) =>
    RustLib.instance.api.crateApiMediaMediaCastNumbers(token: token);

/// Whether this device can make a rendition: a player has loaded libmpv,
/// and the FFmpeg in it is the one this build is bound to. False until the
/// first player has registered (`mpv_stream_register`), and on a desktop
/// whose system FFmpeg is another major. Cheap after the first ask.
bool mediaRenditionsAvailable() =>
    RustLib.instance.api.crateApiMediaMediaRenditionsAvailable();

/// Ends the publication `token`: nothing more is served under it, and a
/// body in flight is cut. Whether it was published.
Future<bool> mediaUnpublish({required String token}) =>
    RustLib.instance.api.crateApiMediaMediaUnpublish(token: token);

/// What `id` is, as JSON: `{name, contentType, len, member, sniffed,
/// inProcess, proxyUrl}` once resolved, or `{refused, message}` when the server will
/// not play it -- a refusal is an answer. Waits while the server adds the
/// torrent and chooses its file (up to the metadata timeout for a
/// magnet), so it runs on a worker; the reader mpv opens afterwards finds
/// the answer kept. Errors when the server is not running.
Future<String> mediaResolve({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaResolve(id: id);

/// The play mpv's reader over `id` will be: this player's `token`
/// (`<viewer>.<screen>`, what `p=` carried) and its read-ahead `buffer`
/// (`normal`, `large`, `maximum`). Set before handing mpv the id; an open
/// without one is an aside, which shares nothing and moves no play.
void mediaSetPlay({
  required String id,
  required String token,
  required String buffer,
}) => RustLib.instance.api.crateApiMediaMediaSetPlay(
  id: id,
  token: token,
  buffer: buffer,
);

/// The viewer changed the read-ahead for `id`. The open reader takes it at
/// its next reopen -- a seek -- and nothing reopens the player for it.
/// Errors when the server is not running or holds nothing under `id`.
void mediaSetBuffer({required String id, required String buffer}) =>
    RustLib.instance.api.crateApiMediaMediaSetBuffer(id: id, buffer: buffer);

/// Where the playback of `id` resumes, in seconds, and how long the film
/// is if the app knows: set right after [`media_set_play`], before mpv is
/// handed the id. A resume of zero is a playback from the top. A hint:
/// never errors.
void mediaSetResume({
  required String id,
  required double resumeSeconds,
  double? runtimeSeconds,
}) => RustLib.instance.api.crateApiMediaMediaSetResume(
  id: id,
  resumeSeconds: resumeSeconds,
  runtimeSeconds: runtimeSeconds,
);

/// The player of `id` is leaving at `position_seconds` of the film:
/// remembered by the server for the next playback resuming near there. A
/// hint: never errors.
Future<void> mediaNotePosition({
  required String id,
  required double positionSeconds,
}) => RustLib.instance.api.crateApiMediaMediaNotePosition(
  id: id,
  positionSeconds: positionSeconds,
);

/// Whether mpv's reader of `id` is waiting on a read now, as JSON
/// (`{waitingMs, offset}`, both null when nothing waits): what the player
/// shows its buffering card from while mpv reports no stall. Cheap; polled.
/// Errors when the server is not running or holds nothing under `id`.
Future<String> mediaReadWait({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaReadWait(id: id);

/// `server_stream_numbers` for what `id` resolved to, as JSON, or null
/// for an id not resolved yet. Errors when the server is not running.
Future<String?> mediaStreamNumbers({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaStreamNumbers(id: id);

/// How long the film behind `id` is (`server_note_duration`, by id). A
/// hint: never errors, and a length that is not one is dropped.
Future<void> mediaNoteDuration({
  required String id,
  required double durationSeconds,
}) => RustLib.instance.api.crateApiMediaMediaNoteDuration(
  id: id,
  durationSeconds: durationSeconds,
);

/// A player opened on `id` (`server_note_player_opened`, by id). A hint:
/// never errors.
Future<void> mediaNotePlayerOpened({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaNotePlayerOpened(id: id);

/// The player of `id` is buffering after having played
/// (`server_note_player_stalled`, by id). A hint: never errors.
Future<void> mediaNotePlayerStalled({required String id}) =>
    RustLib.instance.api.crateApiMediaMediaNotePlayerStalled(id: id);

/// Registers the `xtremio` protocol on the mpv handle at `ctx` (media_kit's
/// `NativePlayer.ctx.address`), resolving libmpv's stream_cb API from the
/// library at `libmpv_path` (`NativeLibrary.path`). Once per player, after
/// `waitForPlayerInitialization` and before the first open; a second call
/// on the same handle is a no-op. Answers whether this call registered it
/// (`false`: it was there already). Errors for a null handle or a libmpv
/// without the API.
Future<bool> mpvStreamRegister({
  required PlatformInt64 ctx,
  required String libmpvPath,
}) => RustLib.instance.api.crateApiMediaMpvStreamRegister(
  ctx: ctx,
  libmpvPath: libmpvPath,
);
