// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Every preference that has been set, as one JSON object
/// (`{"streamsFlat":true}`). An empty object means none has been: a file
/// that is missing, unreadable or not an object all read that way, since a
/// preference is a default the user changed. Errors only before storage has
/// a directory (`core_init`).
Future<String> prefsGetAll() => RustLib.instance.api.crateApiPrefsPrefsGetAll();

/// Stores `value_json` (any JSON value) under `key`, or removes the key
/// when it is null. Every other key in the file is left exactly as it was,
/// including one this build knows nothing about. Writes are atomic
/// (temp-fsync-rename), so a crash mid-write cannot leave half a file.
Future<void> prefsSet({required String key, String? valueJson}) =>
    RustLib.instance.api.crateApiPrefsPrefsSet(key: key, valueJson: valueJson);
