// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Starts the embedded server (idempotent) and returns its base URL, e.g.
/// `http://127.0.0.1:11470/`.
Future<String> serverStart({required ServerConfig config}) =>
    RustLib.instance.api.crateApiServerServerStart(config: config);

/// Stops the embedded server and joins its thread. Ok if it is not running.
Future<void> serverStop() => RustLib.instance.api.crateApiServerServerStop();

/// Base URL of the running embedded server, or null when it is stopped.
String? serverBaseUrl() => RustLib.instance.api.crateApiServerServerBaseUrl();

/// Where and how the embedded server runs. Directories are decided by Dart
/// (path_provider) and created by Rust if missing.
class ServerConfig {
  /// App-support directory for settings.json, logs/, localFiles/.
  final String configDir;

  /// App-cache directory for the torrent piece cache.
  final String cacheDir;

  /// Port on 127.0.0.1; 11470 is stremio-core's default, 0 = ephemeral.
  final int port;

  /// Retry with an ephemeral port if `port` is taken.
  final bool fallbackToEphemeral;

  const ServerConfig({
    required this.configDir,
    required this.cacheDir,
    required this.port,
    required this.fallbackToEphemeral,
  });

  @override
  int get hashCode =>
      configDir.hashCode ^
      cacheDir.hashCode ^
      port.hashCode ^
      fallbackToEphemeral.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          configDir == other.configDir &&
          cacheDir == other.cacheDir &&
          port == other.port &&
          fallbackToEphemeral == other.fallbackToEphemeral;
}
