// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Starts the embedded server (idempotent) and returns its base URL, e.g.
/// `http://127.0.0.1:11470/`.
Future<String> serverStart({required ServerConfig config}) =>
    RustLib.instance.api.crateApiServerServerStart(config: config);

/// Stops the embedded server and joins its thread. Ok if it is not running.
Future<void> serverStop() => RustLib.instance.api.crateApiServerServerStop();

/// Base URL of the running embedded server, or null when it is stopped.
String? serverBaseUrl() => RustLib.instance.api.crateApiServerServerBaseUrl();

/// A torrent's `stats.json` as JSON (camelCase, the shape stremio-core's
/// `Statistics` parses plus the start-up `phase` fields and an optional
/// `error` message): the per-file stats when `file_idx` is set, the
/// torrent-level ones otherwise. `trackers` is the stream's `announce`
/// list, used only if this call is what creates the torrent's engine.
/// Errors when the server is not running, for a negative index, or for an
/// index the torrent does not have once its metadata is known. Blocks the
/// FRB worker while the server answers; never call from the UI thread.
Future<String> serverTorrentStats({
  required String infoHash,
  PlatformInt64? fileIdx,
  required List<String> trackers,
}) => RustLib.instance.api.crateApiServerServerTorrentStats(
  infoHash: infoHash,
  fileIdx: fileIdx,
  trackers: trackers,
);

/// The embedded server's settings as JSON (the `values` of `GET /settings`:
/// `cacheSize`, `btMaxConnections`, ...). Errors when it is not running.
Future<String> serverSettings() =>
    RustLib.instance.api.crateApiServerServerSettings();

/// Applies `patch_json` (a JSON object of settings keys) exactly as
/// `POST /settings` would -- same keys, validation, engine update and
/// persistence -- and returns the settings afterwards as JSON. Errors on
/// malformed JSON, a rejected value, or when the server is not running.
Future<String> serverUpdateSettings({required String patchJson}) => RustLib
    .instance
    .api
    .crateApiServerServerUpdateSettings(patchJson: patchJson);

/// Where and how the embedded server runs. Directories are decided by Dart
/// (path_provider) and created by Rust if missing.
class ServerConfig {
  /// App-support directory for settings.json, logs/, localFiles/.
  final String configDir;

  /// App-cache directory for the torrent piece cache.
  final String cacheDir;

  /// Port on 127.0.0.1; 11470 is stremio-core's default, 0 = ephemeral.
  final int port;

  /// Retry with an ephemeral port if `port` is taken.
  final bool fallbackToEphemeral;

  const ServerConfig({
    required this.configDir,
    required this.cacheDir,
    required this.port,
    required this.fallbackToEphemeral,
  });

  @override
  int get hashCode =>
      configDir.hashCode ^
      cacheDir.hashCode ^
      port.hashCode ^
      fallbackToEphemeral.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          configDir == other.configDir &&
          cacheDir == other.cacheDir &&
          port == other.port &&
          fallbackToEphemeral == other.fallbackToEphemeral;
}
