// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Bytes the volume holding `path` will still give an unprivileged writer,
/// or `null` when that cannot be read.
///
/// This is `statvfs`'s `f_frsize * f_bavail` through `fs4`
/// (`crate::storage::free_bytes`) -- `df`'s Available column, and the same
/// call the embedded server's cache cleaner caps itself with, so the two
/// budgets on one device are measured against one number.
///
/// `path` need not exist yet: the deepest ancestor that does is what gets
/// asked, since a directory nobody has created is still on a volume.
///
/// `null` means unreadable, not full. A caller must leave whatever it would
/// have done alone rather than treat it as no room.
///
/// Signed, because `u64` crosses FRB as a Dart `BigInt` and free space is
/// arithmetic the player does on every tick; `i64` crosses as
/// `PlatformInt64`, which is a plain `int` on every platform this app is
/// built for. A volume with more than eight exabytes free would read as
/// unreadable, which leaves the caller doing nothing -- the same answer it
/// would sensibly give to that much room anyway.
///
/// One `statvfs`. Cheap enough to ask on a timer -- unlike
/// `server_cache_usage`, which is a directory walk -- but it is still a
/// syscall that can block on a slow filesystem, so it stays on an FRB
/// worker rather than being `#[frb(sync)]`.
Future<PlatformInt64?> volumeFreeBytes({required String path}) =>
    RustLib.instance.api.crateApiStorageVolumeFreeBytes(path: path);
