// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Matches the subtitle at `playing_url` to the one at `reference_url`,
/// which the viewer has said is in sync with the video.
///
/// Fetches both, reads when each of them has text on screen and solves for
/// the line between them (`crate::subtitles`). Errors only when a file
/// cannot be fetched -- a pair that does not match is a [`SubtitleMatch`]
/// with `convincing: false` and the score and transform that say so.
///
/// Blocks the FRB worker for the length of two HTTP fetches and a sweep;
/// never call it from the UI thread. The fetches run together, because
/// the second file has nothing to wait for.
Future<SubtitleMatch> subtitlesMatch({
  required String playingUrl,
  required String referenceUrl,
}) => RustLib.instance.api.crateApiSubtitlesSubtitlesMatch(
  playingUrl: playingUrl,
  referenceUrl: referenceUrl,
);

/// What a match found, and the evidence for it.
///
/// The transform is exactly what mpv is told: `sub-speed` is [`ratio`] and
/// `sub-delay` is [`offset`], so a cue at `t` in the playing file lands at
/// `ratio * t + offset`, where the reference file has the same moment.
///
/// [`ratio`]: Self::ratio
/// [`offset`]: Self::offset
class SubtitleMatch {
  /// What the playing file's timestamps are multiplied by.
  final double ratio;

  /// What is added afterwards, in seconds.
  final double offset;

  /// How far above chance the two files have text on screen at the same
  /// moments under this transform: 1 for two files lit over exactly the
  /// same moments, 0 for two doing no better than their own talkativeness
  /// predicts. **This is the number the viewer is shown**, because a
  /// count of cues is not comparable between a file that merges lines and
  /// one that does not -- a translation that merges two lines into one
  /// has half the cues and the same subtitle.
  ///
  /// None when there was nothing to measure: one of the two files has too
  /// few cues to be evidence either way, which is a different answer from
  /// a bad score and is said differently.
  final double? score;

  /// How many cues the playing file has. Not evidence of a match -- it is
  /// here so a file that could not be read as a subtitle at all can be
  /// told from two files that merely disagree, which is what a missing
  /// `score` is reported with.
  final int cues;

  /// How many the reference has, for the same reason.
  final int referenceCues;

  /// Whether the two agree well enough for the transform to be worth
  /// applying. **False is an answer, not an error**: two files for
  /// different episodes, half a film against the whole, or a reference
  /// that is itself adrift all measure, none of them should be applied,
  /// and saying so with the score and the transform is honest where
  /// applying it anyway would ruin a subtitle that was merely a little
  /// out.
  final bool convincing;

  const SubtitleMatch({
    required this.ratio,
    required this.offset,
    this.score,
    required this.cues,
    required this.referenceCues,
    required this.convincing,
  });

  @override
  int get hashCode =>
      ratio.hashCode ^
      offset.hashCode ^
      score.hashCode ^
      cues.hashCode ^
      referenceCues.hashCode ^
      convincing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleMatch &&
          runtimeType == other.runtimeType &&
          ratio == other.ratio &&
          offset == other.offset &&
          score == other.score &&
          cues == other.cues &&
          referenceCues == other.referenceCues &&
          convincing == other.convincing;
}
