// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Matches the subtitle at `playing_url` to the one at `reference_url`,
/// which the viewer has said is in sync with the video.
///
/// Fetches both, reads their cue start times and solves for the line
/// between them (`crate::subtitles`). Errors only when a file cannot be
/// fetched -- a pair that does not match is a [`SubtitleMatch`] with
/// `convincing: false` and the counts that say so.
///
/// Blocks the FRB worker for the length of two HTTP fetches and a sweep;
/// never call it from the UI thread. The fetches run together, because
/// the second file has nothing to wait for.
Future<SubtitleMatch> subtitlesMatch({
  required String playingUrl,
  required String referenceUrl,
}) => RustLib.instance.api.crateApiSubtitlesSubtitlesMatch(
  playingUrl: playingUrl,
  referenceUrl: referenceUrl,
);

/// What a match found, and the evidence for it.
///
/// The transform is exactly what mpv is told: `sub-speed` is [`ratio`] and
/// `sub-delay` is [`offset`], so a cue at `t` in the playing file lands at
/// `ratio * t + offset`, where the reference file has the same moment.
///
/// [`ratio`]: Self::ratio
/// [`offset`]: Self::offset
class SubtitleMatch {
  /// What the playing file's timestamps are multiplied by.
  final double ratio;

  /// What is added afterwards, in seconds.
  final double offset;

  /// How many of the playing file's cue starts land on a cue start of
  /// the reference under this transform.
  final int matched;

  /// How many cue starts the playing file has. `matched` of these is the
  /// evidence the viewer is shown, whichever way the answer went.
  final int cues;

  /// How many the reference has, which is what separates "these two
  /// files disagree" from "the reference was not a subtitle file at
  /// all".
  final int referenceCues;

  /// Whether the two agree well enough for the transform to be worth
  /// applying. **False is an answer, not an error**: two files for
  /// different episodes, half a film against the whole, or a reference
  /// that is itself adrift all score badly, and saying so with the count
  /// is honest where applying the transform anyway would ruin a subtitle
  /// that was merely a little out.
  final bool convincing;

  const SubtitleMatch({
    required this.ratio,
    required this.offset,
    required this.matched,
    required this.cues,
    required this.referenceCues,
    required this.convincing,
  });

  @override
  int get hashCode =>
      ratio.hashCode ^
      offset.hashCode ^
      matched.hashCode ^
      cues.hashCode ^
      referenceCues.hashCode ^
      convincing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleMatch &&
          runtimeType == other.runtimeType &&
          ratio == other.ratio &&
          offset == other.offset &&
          matched == other.matched &&
          cues == other.cues &&
          referenceCues == other.referenceCues &&
          convincing == other.convincing;
}
