import 'package:flutter_test/flutter_test.dart';
import 'package:xtremio/src/rust/api/hello.dart';
import 'package:xtremio/src/rust/frb_generated.dart';

import '../support/rust_lib.dart';

void main() {
  setUpAll(initRustForTests);

  test('Dart and Rust agree on the pinned flutter_rust_bridge version', () {
    // The Rust crate's BRIDGE_VERSION against the version the Dart bindings
    // were generated by: an FRB bump that forgets one side fails here.
    expect(bridgeVersion(), RustLib.instance.codegenVersion);
  });

  test('stremio-core reports its storage schema version', () {
    // SCHEMA_VERSION at the pinned stremio-core rev.
    expect(coreSchemaVersion(), 25);
  });
}
